### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by Enderdead** [chrischoy/MakePytorchPlusPlus#1]
Hi, 
I'm trying to compile your project but I get a link error
```
] $ : python3 setup.py  install --user
running install
running bdist_egg
running egg_info
writing PytorchMakefileTutorial.egg-info/PKG-INFO
writing dependency_links to PytorchMakefileTutorial.egg-info/dependency_links.txt
writing requirements to PytorchMakefileTutorial.egg-info/requires.txt
writing top-level names to PytorchMakefileTutorial.egg-info/top_level.txt
reading manifest file 'PytorchMakefileTutorial.egg-info/SOURCES.txt'
writing manifest file 'PytorchMakefileTutorial.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'MakePytorchBackend' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-sXpGnM/python3.6-3.6.3=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./ -I/home/francois/.local/lib/python3.6/site-packages/torch/lib/include -I/home/francois/.local/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/francois/.local/lib/python3.6/site-packages/torch/lib/include/TH -I/home/francois/.local/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c pybind/bind.cpp -o build/temp.linux-x86_64-3.6/pybind/bind.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MakePytorchBackend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.6-sXpGnM/python3.6-3.6.3=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/pybind/bind.o -Lobjs -L/usr/local/cuda/lib64 -lmake_pytorch -lcudart -o build/lib.linux-x86_64-3.6/MakePytorchBackend.cpython-36m-x86_64-linux-gnu.so
/usr/bin/ld : ne peut trouver -lmake_pytorch
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-g++' failed with exit status 1
```
Maybe a path problem ? Have you some idea to fix my error ?
thank you in advance

**Comment by chrischoy** [comment]
Have you compiled first? You have to make it and it will also call setup when it finishes compilation.

**Comment by chrischoy** [comment]
Updated the `README.md` and `setup.py` to use python setup instead of the command `make`

**Comment by hengheng728** [comment]
Hi, 

I also get the similar error, do you have any suggestion?

Thank you very much!

CUDA -- Version 10.0
Pytorch --Version 1.3.1

`NVCC src/add.cu
nvcc -std=c++11 -ccbin=g++ -Xcompiler -fPIC -DNDEBUG -O3 -I./ -I/usr/include -I/home/cvjz3/anaconda3/envs/torch_env/include/python3.7m -I/home/cvjz3/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/include -I/home/cvjz3/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cvjz3/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/include/TH -I/home/cvjz3/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/include/THC -DTORCH_API_INCLUDE_EXTENSION_H -D_GLIBCXX_USE_CXX11_ABI=1 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61 -M src/add.cu -o objs/cuda/add.d \
        -odir objs/cuda
nvcc fatal   : Unsupported gpu architecture 'compute_60'
Makefile:96: recipe for target 'objs/cuda/add.o' failed
make: *** [objs/cuda/add.o] Error 1
running install
running bdist_egg
running egg_info
writing PytorchMakefileTutorial.egg-info/PKG-INFO
writing dependency_links to PytorchMakefileTutorial.egg-info/dependency_links.txt
writing requirements to PytorchMakefileTutorial.egg-info/requires.txt
writing top-level names to PytorchMakefileTutorial.egg-info/top_level.txt
reading manifest file 'PytorchMakefileTutorial.egg-info/SOURCES.txt'
writing manifest file 'PytorchMakefileTutorial.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'MakePytorchBackend' extension
gcc -pthread -B /home/cvjz3/anaconda3/envs/torch_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./ -I/home/cvjz3/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/include -I/home/cvjz3/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cvjz3/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/include/TH -I/home/cvjz3/anaconda3/envs/torch_env/lib/python3.7/site-packages/torch/include/THC -I/home/cvjz3/anaconda3/envs/torch_env/include/python3.7m -c pybind/bind.cpp -o build/temp.linux-x86_64-3.7/pybind/bind.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MakePytorchBackend -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/cvjz3/anaconda3/envs/torch_env/compiler_compat -L/home/cvjz3/anaconda3/envs/torch_env/lib -Wl,-rpath=/home/cvjz3/anaconda3/envs/torch_env/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/pybind/bind.o -Lobjs -L/usr/lib -lmake_pytorch -lcudart -o build/lib.linux-x86_64-3.7/MakePytorchBackend.cpython-37m-x86_64-linux-gnu.so
/home/cvjz3/anaconda3/envs/torch_env/compiler_compat/ld: cannot find -lmake_pytorch
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1`

**Comment by chrischoy** [comment]
It says

fatal : Unsupported gpu architecture 'compute_60' 

Your GPU does not support SM 6.0. Please remove the line that defines compute_60

**Comment by hengheng728** [comment]
> It says
> 
> fatal : Unsupported gpu architecture 'compute_60'
> 
> Your GPU does not support SM 6.0. Please remove the line that defines compute_60

Thank you very much!
